---
collections:
  - name: ovirt.ovirt
  - name: ansible.posix
  - name: awx.awx
  - name: community.general
  - name: community.postgresql
  - name: oracle.oci
  - name: containers.podman
  - name: community.crypto
