- name: Add olcne ol8 repository
  dnf:
    name: oracle-olcne-release-el8
    state: latest

- name: Enable ol8 current ocne repo
  shell:
    cmd: dnf config-manager --enable ol8_olcne18 ol8_addons ol8_baseos_latest ol8_appstream ol8_kvm_appstream ol8_UEKR7

- name: Disable ol8 old ocne repos
  shell:
    cmd: dnf config-manager --disable ol8_olcne12 ol8_olcne13 ol8_olcne14 ol8_olcne15 ol8_olcne16 ol8_olcne17 ol8_developer
