---
# Copyright (c) 2024 Oracle and/or its affiliates.
# This software is made available to you under the terms of the Universal Permissive License (UPL), Version 1.0.
# The Universal Permissive License (UPL), Version 1.0 (see COPYING or https://oss.oracle.com/licenses/upl)
# See LICENSE.TXT for details.

- name: OCNE OS pre-installation steps
  hosts: operator,controlplane,worker
  collections:
    - ansible.posix
    - community.general
  become: yes
  vars_files:
    - default_vars.yaml
    - oci_vars.yaml

  tasks:

  # SELinux for iptables
  # https://bugzilla.redhat.com/show_bug.cgi?id=2008097

  - name: Write cil selinux policy file
    ansible.builtin.shell: |
      echo '(allow iptables_t cgroup_t (dir (ioctl)))' > /home/{{ username }}/local_iptables.cil

  - name: Add selinux module
    ansible.builtin.shell: |
      semodule -i /home/{{ username }}/local_iptables.cil

  - name: Setup olcne ol8 repos
    ansible.builtin.include_tasks: ol8-repo-config.yaml
    when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '8'

  - name: Setup olcne ol9 repos
    ansible.builtin.include_tasks: ol9-repo-config.yaml
    when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '9'

  - name: Install chrony
    ansible.builtin.dnf:
      name: chrony
      state: latest

  - name: Enable chrony service
    ansible.builtin.systemd_service:
      name: chronyd
      state: started
      enabled: yes

  - name: Disable swap
    ansible.builtin.shell: |
      swapoff -a

  - name: Disable swap in fstab
    ansible.builtin.replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'

- name: OCNE installation steps
  hosts: operator
  collections:
    - ansible.posix
    - community.general
  become: yes
  vars_files:
    - default_vars.yaml
    - oci_vars.yaml

  vars:
    operator_nodes: "{{ range(groups['operator']|length|int) | map('extract',groups['operator'])|list | map('regex_replace', '^(.*)$', '\\1' ) | join(',') }}"
    control_nodes: "{{ range(groups['controlplane']|length|int) | map('extract',groups['controlplane'])|list | map('regex_replace', '^(.*)$', '\\1' + ':8090' ) | join(',') }}"
    worker_nodes: "{{ range(groups['worker']|length|int) | map('extract',groups['worker'])|list | map('regex_replace', '^(.*)$', '\\1' + ':8090' ) | join(',') }}"
    # operator_nodes_fqdn: "{{ range(groups['operator']|length|int) | map('extract',groups['operator'])|list | map('regex_replace', '^(.*)$', '\\1' + '.' + my_subnet_domain_name ) | join(',') }}"
    # control_nodes_fqdn: "{{ range(groups['controlplane']|length|int) | map('extract',groups['controlplane'])|list | map('regex_replace', '^(.*)$', '\\1' + '.' + my_subnet_domain_name ) | join(',') }}"
    # worker_nodes_fqdn: "{{ range(groups['worker']|length|int) | map('extract',groups['worker'])|list | map('regex_replace', '^(.*)$', '\\1' + '.' + my_subnet_domain_name ) | join(',') }}"
    all_nodes: "{{ range(groups['all']|length|int) | map('extract',groups['all'])|list | map('regex_replace', '^(.*)$', '\\1' ) | join(',') }}"
    ocne_registry_location: 'container-registry.oracle.com/olcne'

  tasks:

  - name: Print OCI compartment_ocid
    ansible.builtin.debug:
      msg: OCI compartment OCID is {{ my_compartment_id }}
    when: debug_enabled

  - name: Print OCI vcn_ocid
    ansible.builtin.debug:
      msg: OCI vcn OCID is {{ my_vcn_id }}
    when: debug_enabled

  - name: Print OCI lb_subnet_ocid
    ansible.builtin.debug:
      msg: OCI lb_subnet OCID is {{ my_subnet_id }}
    when: debug_enabled

  - name: Print vcn subnet_domain_name
    ansible.builtin.debug:
      msg: OCI Subnet Domain Name is {{ my_subnet_domain_name }}
    when: 
      - debug_enabled
  
  - name: Print string of all operator nodes comma separated
    ansible.builtin.debug:
      msg: "{{ operator_nodes }}"
    when: 
      - debug_enabled
  
  - name: Print string of all control plane nodes comma separated
    ansible.builtin.debug:
      msg: "{{ control_nodes }}"
    when: 
      - debug_enabled
  
  - name: Print string of all worker nodes comma separated
    ansible.builtin.debug:
      msg: "{{ worker_nodes }}"
    when: 
      - debug_enabled
  
  - name: Print string of all nodes comma separated
    ansible.builtin.debug:
      msg: "{{ all_nodes }}"
    when: 
      - debug_enabled

  - name: Add compartment variable to .bashrc
    ansible.builtin.blockinfile:
      dest: /home/oracle/.bashrc
      block: |
        export COMPARTMENT_OCID={{ my_compartment_id }}
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
      insertafter: EOF
      owner: "{{ username }}"

  - name: Install oci-cli on ol8
    ansible.builtin.dnf:
      name: ['python36-oci-cli', 'jq']
      enablerepo: ol8_developer
      state: latest
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_major_version'] == "8"

  - name: Install oci-cli on ol9
    ansible.builtin.dnf:
      name: ['python39-oci-cli', 'jq']
      state: latest
    when:
      - ansible_facts['distribution'] == "OracleLinux"
      - ansible_facts['distribution_major_version'] == "9"

  - name: Add operator firewall rules
    ansible.posix.firewalld:
      port: 8091/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Add control plane firewall rules
    ansible.posix.firewalld:
      port: "{{ item[1] }}"
      permanent: yes
      state: enabled
      immediate: yes
    delegate_to: "{{ item[0] }}"
    loop: "{{ groups['controlplane'] | product(['2379/tcp','2380/tcp','6443/tcp','8090/tcp','8472/udp','10250/tcp','10255/tcp','10251/tcp','10252/tcp']) | list }}"

  - name: Add worker firewall rules
    ansible.posix.firewalld:
      port: "{{ item[1] }}"
      permanent: yes
      state: enabled
      immediate: yes
    delegate_to: "{{ item[0] }}"
    loop: "{{ groups['worker'] | product(['8090/tcp','10250/tcp','10255/tcp','8472/udp']) | list }}"

  - name: Add cni0 firewall rule
    ansible.posix.firewalld:
      zone: trusted
      interface: cni0
      permanent: yes
      state: enabled
      immediate: yes
    delegate_to: "{{ item }}"
    loop: "{{ (groups['controlplane'] + groups['worker']) }}"

  - name: Load br_netfilter module
    community.general.modprobe:
      name: br_netfilter
      state: present
    delegate_to: "{{ item }}"
    loop: "{{ (groups['controlplane'] + groups['worker']) }}"

  - name: Ensure br_netfilter module loads on boot
    ansible.builtin.shell: |
      echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf
    delegate_to: "{{ item }}"
    loop: "{{ (groups['controlplane'] + groups['worker']) }}"

  - name: Disable docker and containerd services
    ansible.builtin.systemd_service:
      name: "{{ item[1] }}"
      state: stopped
      enabled: no
    when: ansible_facts.services['docker.service'] is defined or ansible_facts.servcices['containerd.service'] is defined
    delegate_to: "{{ item[0] }}"
    loop: "{{ (groups['controlplane'] + groups['worker']) | product(['docker.service','containerd.service']) | list }}"

  - name: Install olcne packages on operator
    ansible.builtin.dnf:
      name: 
        - olcnectl
        - olcne-api-server
        - olcne-utils
      state: latest

  - name: Install olcne packages on control plane and worker
    ansible.builtin.dnf:
      name: 
        - olcne-utils
        - olcne-agent
      state: latest
    delegate_to: "{{ item }}"
    loop: "{{ (groups['controlplane'] + groups['worker']) }}"

  - name: Check if OCNE provisioned
    ansible.builtin.stat:
      path: ~/.ocne-provisioned
    become_user: "{{ username }}"
    register: ocne_provision

  - name: Enable olcne api-server and agent service
    ansible.builtin.systemd_service:
      name: olcne-api-server
      state: stopped
      enabled: yes
    when: not ocne_provision.stat.exists

  - name: Enable olcne api-server and agent service
    ansible.builtin.systemd_service:
      name: olcne-agent
      state: stopped
      enabled: yes
    when: not ocne_provision.stat.exists
    delegate_to: "{{ item }}"
    loop: "{{ (groups['controlplane'] + groups['worker']) }}"

  - name: Add user to olcne group
    ansible.builtin.user:
      name: "{{ username }}"
      groups: olcne
      append: true

  - name: Reset ssh connection to allow user changes to affect 'current login user'
    ansible.builtin.meta: reset_connection

  - name: Check if OCNE provisioned
    ansible.builtin.stat:
      path: ~/.ocne-provisioned
    become_user: "{{ username }}"
    register: ocne_provision

  - name: Create Certificates for Kubernetes Nodes
    ansible.builtin.shell: |
      olcnectl certificates distribute --cert-dir ~/certificates/ --nodes {{ all_nodes }}
    become_user: "{{ username }}"
    when: not ocne_provision.stat.exists
 
  - name: Create Certificates for the Platform CLI
    ansible.builtin.shell: |
      olcnectl certificates generate --nodes {{ operator_nodes }},127.0.0.1 \
      --cert-dir ~/.olcne/certificates/{{ operator_nodes }}:8091/  \
      --byo-ca-cert ~/certificates/ca/ca.cert \
      --byo-ca-key ~/certificates/ca/ca.key \
      --one-cert
    become_user: "{{ username }}"
    when: not ocne_provision.stat.exists

  - name: Copy CA Certificate for the Platform CLI
    ansible.builtin.copy:
      src: ~/certificates/ca/ca.cert
      dest: ~/.olcne/certificates/ocne-operator:8091/ca.cert
      remote_src: true
    become_user: "{{ username }}"
    when: not ocne_provision.stat.exists    

  # - name: Workaround for permissions on certificate files due to Ansible
  #   ansible.builtin.file:
  #     path: '/etc/olcne/certificates/{{ item }}.cert'
  #     mode: '0640'
  #   loop:
  #     - node
  #     - ca
  #   when: not ocne_provision.stat.exists

  - name: Start OLCNE API Server with Certificate
    ansible.builtin.shell: |
      /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-component api-server
    when: not ocne_provision.stat.exists

  - name: Start OLCNE Agent with the Certificates
    become: yes
    ansible.builtin.shell: |
      /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-component agent
    delegate_to: "{{ item }}"
    loop: "{{ groups['controlplane'] }}"
    when: not ocne_provision.stat.exists

  - name: Start OLCNE Agent with the Certificates
    become: yes
    ansible.builtin.shell: |
      /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-component agent
    delegate_to: "{{ item }}"
    loop: "{{ groups['worker'] }}"
    when: not ocne_provision.stat.exists
    
  - name: Create Certificates for ExternalIPs service
    ansible.builtin.shell: |
      olcnectl certificates generate \
      --nodes externalip-validation-webhook-service.externalip-validation-system.svc,externalip-validation-webhook-service.externalip-validation-system.svc.cluster.local \
      --cert-dir /home/{{ username }}/certificates/restrict_external_ip/ \
      --byo-ca-cert /home/{{ username }}/certificates/ca/ca.cert \
      --byo-ca-key /home/{{ username }}/certificates/ca/ca.key \
      --one-cert
    become_user: "{{ username }}"
    when: not ocne_provision.stat.exists

  - name: Copy CA Certificate for the ExternalIP service
    ansible.builtin.copy:
      src: ~/certificates/ca/ca.cert
      dest: ~/certificates/restrict_external_ip/ca.cert
      remote_src: true
    become_user: "{{ username }}"
    when: not ocne_provision.stat.exists
        
  - name: Include steps to fully install ocne      
    ansible.builtin.include_tasks: provision-ocne-full.yaml
    when: 
      - not ocne_provision.stat.exists
      - use_ocne_full

  - name: Check if OCNE provisioned
    ansible.builtin.stat:
        path: ~/.ocne-provisioned
    become_user: "{{ username }}"
    register: ocne_provision

  - name: Include oci-ccm bash env vars
    ansible.builtin.include_tasks: preconfig-oci-ccm.yaml
    when: oci_ccm_bash

  - name: Provision oci-ccm
    ansible.builtin.include_tasks: "provision-oci-ccm.yaml"
    when: 
      - ocne_provision.stat.exists
      - ocne_type != 'none'
      - use_oci_ccm

  - name: Provision kubectl
    ansible.builtin.include_tasks: "provision-kubectl.yaml"
    when: 
      - ocne_provision.stat.exists
      - ocne_type != 'none'