- name: Add olcne ol9 repository
  dnf:
    name: oracle-olcne-release-el9
    state: latest

- name: Enable ol9 current ocne repo
  shell:
    cmd: dnf config-manager --enable ol9_olcne18 ol9_addons ol9_baseos_latest ol9_appstream ol9_UEKR7

- name: Disable ol9 old repos
  shell:
    cmd: dnf config-manager --disable ol9_olcne17 ol9_developer
