---
- name: Gather facts for localhost
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Get minimum set of available facts
    ansible.builtin.setup:
      gather_subset:
        - 'min'
    register: min_facts

  - name: Print minimum set of facts
    ansible.builtin.debug:
      msg: "{{ min_facts }}"

  - name: Print system date
    ansible.builtin.debug:
      var: ansible_date_time.date
